services:
  kafka:
    container_name: ms_kafka
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - microservices-net
    ports:
      - "9092:9092"

  mail-dev:
    container_name: ms_mail_dev
    image: maildev/maildev
    ports:
      - "1025:1025"
      - "1080:1080"

  mongo-express:
    container_name: ms_mongo_express
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINPASSWORD: luis2
      ME_CONFIG_MONGODB_ADMINUSERNAME: luis2
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    restart: always

  mongodb:
    container_name: ms_mongo_db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_PASSWORD: luis2
      MONGO_INITDB_ROOT_USERNAME: luis2
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data

  pgadmin:
    container_name: ms_pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    networks:
      - microservices-net
    ports:
      - "5050:80"
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin

  postgres:
    container_name: ms_pg_sql
    image: postgres
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: luis2
      POSTGRES_USER: postgres
    networks:
      - microservices-net
    ports:
      - "5433:5433"
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data

  zookeeper:
    container_name: ms_zookeeper
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - microservices-net
    ports:
      - "22181:2181"

networks:
  microservices-net:
    driver: bridge

volumes:
  mongo:
  pgadmin:
  postgres:
